### PR TITLE
Fix ReturnAndSet() compile error when using incompatible argument types

### LINKED ISSUE #265: ReturnAndSet won't compile with different argument types
Hi,

given the following snippet:
`
    class X {
    public:
        virtual int f(std::string&, std::vector<std::string>&) = 0;
    };
    Mock<X> mockX;
    std::vector<std::string> d{"S"};
    When(Method(mockX, f)).ReturnAndSet(20, std::placeholders::_2 <= d);
`

Results the following compiler error:
`
esser-thirdparty/FakeIt/single_header/boost/fakeit.hpp:7730:58: error: no viable overloaded '=' [clang-diagnostic-error]
                    GetArg(std::forward<current_arg>(p)) = std::get<check_index>(arg_vals).value;
                                                         ^
FakeIt/single_header/boost/fakeit.hpp:7746:54: note: in instantiation of function template specialization 'fakeit::helper::ArgLocator<1, 0>::AssignArg<std::basic_string<char> &, std::vector<std::basic_string<char>> &, 2>' requested here
            ArgLocator<arg_index, sizeof...(N) - 1>::AssignArg(std::forward<current_arg>(p), arg_vals);
                                                     ^
FakeIt/single_header/boost/fakeit.hpp:7506:29: note: in instantiation of function template specialization 'fakeit::helper::Assign<1, std::basic_string<char> &, std::vector<std::basic_string<char>> &, 2, std::vector<std::basic_string<char>> &>' requested here
                    helper::Assign<1>(vals_tuple, std::forward<arglist>(args)...);
                            ^
FakeIt/single_header/boost/fakeit.hpp:7498:19: note: in instantiation of member function 'fakeit::MethodStubbingProgress<int, std::basic_string<char> &, std::vector<std::basic_string<char>> &>::GetAssigner(int &&, helper::ArgValue<vector<basic_string<char>> &, 2>)::Lambda::operator()' requested here
            class Lambda {
                  ^
FakeIt/single_header/boost/fakeit.hpp:7427:23: note: in instantiation of function template specialization 'fakeit::MethodStubbingProgress<int, std::basic_string<char> &, std::vector<std::basic_string<char>> &>::GetAssigner<std::vector<std::basic_string<char>> &, 2>' requested here
            return Do(GetAssigner(std::forward<R>(r),
                      ^
.cpp:46:28: note: in instantiation of function template specialization 'fakeit::MethodStubbingProgress<int, std::basic_string<char> &, std::vector<std::basic_string<char>> &>::ReturnAndSet<fakeit::helper::ArgValue<std::vector<std::basic_string<char>> &, 2>>' requested here
    When(Method(mockX, f)).ReturnAndSet(20, std::placeholders::_2 <= d);
                           ^
/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/basic_string.h:665:7: note: candidate function not viable: no known conversion from 'std::vector<std::basic_string<char>>' to 'const std::basic_string<char>' for 1st argument
      operator=(const basic_string& __str)
      ^
/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/basic_string.h:675:7: note: candidate function not viable: no known conversion from 'std::vector<std::basic_string<char>>' to 'const char *' for 1st argument
      operator=(const _CharT* __s)
      ^
/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/basic_string.h:686:7: note: candidate function not viable: no known conversion from 'std::vector<std::basic_string<char>>' to 'char' for 1st argument
      operator=(_CharT __c)
      ^
/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/basic_string.h:703:7: note: candidate function not viable: no known conversion from 'std::vector<std::basic_string<char>>' to 'std::basic_string<char>' for 1st argument
      operator=(basic_string&& __str)
      ^
/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/basic_string.h:771:7: note: candidate function not viable: no known conversion from 'std::vector<std::basic_string<char>>' to 'initializer_list<char>' for 1st argument
      operator=(initializer_list<_CharT> __l)
      ^
/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/basic_string.h:785:8: note: candidate template ignored: requirement '__and_<std::is_convertible<const std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char>>>> &, std::basic_string_view<char, std::char_traits<char>>>, std::__not_<std::is_convertible<const std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char>>>> *, const std::basic_string<char, std::char_traits<char>, std::allocator<char>> *>>, std::__not_<std::is_convertible<const std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char>>>> &, const char *>>>::value' was not satisfied [with _Tp = std::vector<std::basic_string<char>>]
       operator=(const _Tp& __svt)
       ^
4 warnings and 4 errors generated.
`
But if I change the interface method signature, to match in type of arguments, everything compiles well:
`class X {
public:
    virtual int f(std::vector<std::string>&, std::vector<std::string>&) = 0;
};
`

About env:
- CMake: 3.20
- g++ / gcc 11
- c++20 standard

Isn't it possible to use ReturnAndSet if method has different types of arguments?

### PR DESCRIPTION
**Pull request by hedayat**
Fixes #265

It present a sub-optimal solution for C++ < 17, since it catches type incompatibility problems at runtime rather than during compile time. But at least, it works. 

It is probably possible to make it work at compile time, specially for C++14; but I'm not sure I'll go for it.

### CODE REVIEW

File: tests/stubbing_tests.cpp [hunk 1]
```diff
@@ -166,6 +167,8 @@ struct BasicStubbing : tpunit::TestFixture {
         Mock<SomeInterface> mock;
         When(Method(mock, funcRefArgs)).ReturnAndSet(1, _2 <= 3, _1 <= 2);
         When(Method(mock, procRefArgs)).ReturnAndSet(_1 <= 4, _2 <= 5).ReturnAndSet( _2 <= 6, _1 <= 7).ReturnAndSet(_2 <= 8);
+        std::vector<std::string> v{"str"};
```
Comment (malcolmdavey) [inline tests/stubbing_tests.cpp:170]: Might be nicer to have separate test functions. Otherwise it's becoming quite complicated and harder to read/maintain.

Comment (hedayat) [reply tests/stubbing_tests.cpp:170]: I'd do it if you think so. 

Unfortunately, the number of test cases in a TestFixture is [currently limited ](https://github.com/eranpeer/FakeIt/blob/a71cbd690e3c7b307e63ea3e359e53f57f9b4845/tests/tpunit%2B%2B.hpp#L240)and it should be manually increased. Which is annoying. So, I was reluctant to separate a test case to multiple test cases.

Comment (malcolmdavey) [reply tests/stubbing_tests.cpp:170]: Hmmm.
Looking up TPUnit seems latest versions might not have such restrictions.
https://github.com/tpounds/tpunitpp

Might not want to update too much in one Pull Request though.

Comment (hedayat) [reply tests/stubbing_tests.cpp:170]: That's good to know. So I'll go and split this test. 

And yeah, I agree; specially since I won't reach the limit in this PR. We can make a separate PR for updating TPUnit.

File: include/fakeit/StubbingProgress.hpp [hunk 2]
```diff
@@ -425,11 +425,36 @@ namespace fakeit {
...
             template<typename current_arg, typename ...T, int ...N>
             static void AssignArg(current_arg &&p, std::tuple<ArgValue<T, N>...> arg_vals) {
-                if (std::get<check_index>(arg_vals).pos == arg_index)
+#if __cplusplus >= 201703L
+                if constexpr (std::get<check_index>(arg_vals).pos == arg_index)
                     GetArg(std::forward<current_arg>(p)) = std::get<check_index>(arg_vals).value;
+#else
+                if (std::get<check_index>(arg_vals).pos == arg_index)
+                    Set(std::forward<current_arg>(p), std::get<check_index>(arg_vals).value);
+#endif
```
Comment (FranckRJ) [inline include/fakeit/StubbingProgress.hpp:434]: Technically speaking `if constexpr` is just a syntactic sugar for template stuff, so it should be possible to have it as well in pre-C++17 I guess.

```cpp
void post_cpp17()
{
    if constexpr (true)
        {/*stuff*/}
    else
        {/*other stuff*/}
}

template <bool B>
void ifConstexprCompat() {/*stuff*/}

template <>
void ifConstexprCompat<false>() {/*other stuff*/}

void pre_cpp17()
{
    ifConstexprCompat<true>();
}
```

It would remove the need for exceptions.

**Review by FranckRJ — CHANGES_REQUESTED** [review]

File: include/fakeit/StubbingProgress.hpp (hunk 2 above)
Comment (hedayat) [reply include/fakeit/StubbingProgress.hpp:434]: Yeah, I said it should be probably possible, but I'm not really up for it. Specially since std::get is not constexpr in C++11, it should need some work in that area too. 

BTW, edits are allowed so if somebody is willing to fix it, it's completely OK. I might also go for it, but probably takes some time.

Comment (FranckRJ) [reply include/fakeit/StubbingProgress.hpp:434]: > std::get is not constexpr in C++11

Didn't knew, it's a bit annoying then I agree.

File: tests/stubbing_tests.cpp (hunk 1 above)
Comment (hedayat) [reply tests/stubbing_tests.cpp]: Done.

**Comment by FranckRJ** [comment]
I'll look into it this weekend. I'll try as well to make the static check compatible for C++11 (or maybe at least C++14) but I'm afraid that, as you said, it will be a bit too complicated.

**Comment by hedayat** [comment]
> I'll look into it this weekend. I'll try as well to make the static check compatible for C++11 (or maybe at least C++14) but I'm afraid that, as you said, it will be a bit too complicated.

That'd be great. I'm sorry that I'm a bit lazy to work on C++11 compatibility (I consider it too old these days :P ).

**Review by FranckRJ — APPROVED** [review]

**Comment by FranckRJ** [comment]
I'll admit that I'm a bit lazy as well. I'll ship it like that because it fix a bug so the faster it's in a release the better, and support for older versions of C++ can still be improved in a future update, so it's OK I guess.
